apiVersion: v1
kind: Service
metadata:
  name: ubt-am
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ubtam.labels" . | nindent 4 }}
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector: {{ include "ubtam.matchLabels" . | nindent 4 }}
