# local deploy only
version: '3'
services:
  agent-eth:
    image: 'ubtr/agent-eth:${UBT_AGENTS_VERSION}'
    ports:
      - '50051:50051'
    volumes:
      - './config.yml:/config.yml'
    command: ['--config', '/config.yml', '--log', 'DEBUG', "-r"]
  postgres:
    image: postgres:15.5
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: am
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  am:
    image: 'ubtr/am:${UBT_AGENTS_VERSION}'
    command: ['--log', 'DEBUG', "--db", "host=postgres user=postgres password=postgres dbname=am"]
    depends_on:
      - postgres
    ports:
      - '50052:50052'
